server:
  port: 8080
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: webviews
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    enabled: true

db:
  product:
    url: jdbc:mysql://localhost:3306/dev_erp?useUnicode=true&characterEncoding=utf8
    username: dev_user
    password: zxcv123

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:melo@localhost:8001/eureka/

EUREKASERVERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

config:
  loginUrl: http://EUREKASERVERPROVIDER/login

#访问地址：http://localhost:8080/hystrix，输入http://localhost:8080/hystrix.stream,点击monitor Stream进入监控页面